server:
  port: 8070
#  servlet:
#    context-path: /school
spring:
  application:
    name: schools
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/schools
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  config:
    import: optional:configserver:http://localhost:8888

application:
  config:
    students-url: "http://localhost:8090/api/v1/students"

eureka:
  instance:
    hostname: localhost
    appname: school
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka